import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ApiService {
  banners = [
    { banner: 'assets/images/1.jpg' },
    { banner: 'assets/images/2.jpg' },
    { banner: 'assets/images/3.jpg' },
  ];
  restaurants = [
    {
      uid: 'qdnjdvugdugvuggvuggug',
      cover: 'assets/images/1.jpg',
      name: 'Burger Farm',
      cuisines: ['Italian', 'Mexican'],
      rating: 5,
      delivery_time: 25,
      price: 100,
      distance: 2.5,
    },
    {
      uid: 'qdnjdvugdugvuggauggug',
      cover: 'assets/images/2.jpg',
      name: 'Burger King',
      cuisines: ['Italian', 'Mexican'],
      rating: 4,
      delivery_time: 15,
      price: 200,
      distance: 1.5,
    },
    {
      uid: 'qdnjdvugdugvuggbuggug',
      cover: 'assets/images/3.jpg',
      name: 'Burger Chacha',
      cuisines: ['Italian', 'Mexican'],
      rating: 5,
      delivery_time: 10,
      price: 150,
      distance: 0.5,
    },
  ];

  allRestaurants = [
    {
      uid:'qdnjdvugdugvuggvuggug',
      cover: 'assets/images/1.jpg',
      name: 'Burger Farm',
      shortname: 'burger farm',
      cuisines: ['Italian', 'Mexican'],
      rating: 5,
      delivery_time: 25,
      price: 100,
    },
    {
      uid:'qdnjdvugdugvuggauggug',
      cover: 'assets/images/2.jpg',
      name: 'Burger King',
      shortname: 'burger king',
      cuisines: ['Italian', 'Mexican'],
      rating: 4,
      delivery_time: 15,
      price: 200,
    },
    {
      uid:'qdnjdvugdugvuggbuggug',
      cover: 'assets/images/3.jpg',
      name: 'Burger Chacha',
      shortname: 'burger chacha',
      cuisines: ['Italian', 'Mexican'],
      rating: 5,
      delivery_time: 10,
      price: 150,
    },
  ];

  restaurants1 = [
    {
      uid: 'qdnjdvugdugvuggvuggug',
      cover: 'assets/images/1.jpg',
      name: 'Burger Farm',
      address: 'BapuSapalya,Karnatak,INDIA',
      cuisines: ['Italian', 'Mexican'],
      rating: 5,
      delivery_time: 25,
      price: 100,
      distance: 2.5,
    },
    {
      uid: 'qdnjdvugdugvuggauggug',
      cover: 'assets/images/2.jpg',
      name: 'Burger King',
      address: 'RaMurthiNagar,Karnatak,INDIA',
      cuisines: ['Italian', 'Mexican'],
      rating: 4,
      delivery_time: 15,
      price: 200,
      distance: 1.5,
    },
    {
      uid: 'qdnjdvugdugvuggbuggug',
      cover: 'assets/images/3.jpg',
      name: 'Burger Chacha',
      address: 'Bell Outlet,Karnatak,INDIA',
      cuisines: ['Italian', 'Mexican'],
      rating: 5,
      delivery_time: 10,
      price: 150,
      distance: 0.5,
    },
  ];

  addresses = [
    {
      address: 'Bapu Sapalaya, India',
      house: '1st Floor',
      id: '7Kox63KlggTvV7ebRKar',
      landmark: 'Bapu Sapalaya Bazar',
      lat: 26.1830738,
      lng: 91.74049769999999,
      title: 'Home',
      user_id: '1',
    },
    {
      address: 'Zibtek, India',
      house: '2nd Floor',
      id: '8Kox63KlggTvV7ebRKar',
      landmark: 'Ramurthi Nagar',
      lat: 26.1830738,
      lng: 91.74049769999999,
      title: 'Work',
      user_id: '1',
    },
  ];


  categories: any[] = [
    {
      id: 'e00',
      name: 'Italian',
      uid: 'qdnjdvugdugvuggvuggug',
    },
    {
      id: 'e0',
      name: 'Mexican',
      uid: 'qdnjdvugdugvuggvuggug',
    },
  ];

  allItems = [
    {
      category_id: 'e00',
      cover: 'assets/images/pizza.jpg',
      desc: 'Great in taste,You fall in love with this definitely',
      id: 'i1',
      name: 'Pizza',
      price: 120,
      rating: 0,
      status: true,
      uid: 'qdnjdvugdugvuggvuggug',
      variation: false,
      veg: false,
    },
    {
      category_id: 'e0',
      cover: 'assets/images/salad.jpg',
      desc: 'Great in taste best in Bengaluru',
      id: 'i2',
      name: 'Caprese Salad',
      price: 200,
      rating: 0,
      status: true,
      uid: 'qdnjdvugdugvuggvuggug',
      variation: false,
      veg: true,
    },
    {
      category_id: 'e00',
      cover: 'assets/images/pasta.jpg',
      desc: 'Great in taste,You Love This food gwiggy assured',
      id: 'i3',
      name: 'Pasta',
      price: 150,
      rating: 0,
      status: true,
      uid: 'qdnjdvugdugvuggvuggug',
      variation: false,
      veg: true,
    },
  ];

  orders = [
    {
      address: {
        address: 'Ramurthi Nagar Rd, Bengaluru,Karnataka, India',
        house: 'dsgd',
        id: 'cLQdnS8YXk5HTDfM3UQC',
        landmark: 'fdgs',
        lat: 26.108991978867923,
        lng: 91.79069981213378,
        title: 'yui',
        user_id: 'UA5JWxgjDOYgfXe92H0pFHwulTz2',
      },
      deliveryCharge: 20,
      grandTotal: '540.00',
      id: '5aG0RsPuze8NX00B7uRP',
      order: [
        {
          category_id: 'e10',
          cover: 'assets/imgs/baha.jpg',
          desc: 'Great in taste',
          id: 'i32',
          name: 'Bahamas',
          price: 270,
          quantity: 1,
          rating: 0,
          status: true,
          uid: 'r5',
          variation: false,
          veg: false,
        },
        {
          category_id: 'e10',
          cover: 'assets/imgs/mofo.jpg',
          desc: 'Great in taste',
          id: 'i33',
          name: 'Mofongo',
          price: 250,
          quantity: 1,
          rating: 0,
          status: true,
          uid: 'r5',
          variation: false,
          veg: true,
        },
      ],
      paid: 'COD',
      restaurant: {
        address: 'Bapu Sapalaya, India',
        city: '909090567',
        closeTime: '21:00',
        cover: '',
        cuisines: ['Caribbean food', 'North Indian', 'Vietnamese'],
        delivery_time: 25,
        description: 'dd',
        email: 'BURGERFARM@gmail.com',
        latitude: 26.1286243,
        longitude: 91.8012675,
        id: 'r5',
        isClose: true,
        name: 'Burger Farm',
        openTime: '07:00',
        phone: 6619563867,
        price: 27,
        rating: 4.7,
        short_name: 'burger farm',
        status: 'open',
        totalRating: 13,
      },
      restaurant_id: 'r5',
      status: 'created',
      time: 'Jul 6, 2022 11:44 AM',
      total: '520.00',
      user_id: '1',
    },
    {
      address: {
        address: 'Indira Nagar Rd, Borsojai, Basistha 781029, India',
        house: 'dsgd',
        id: 'cLQdnS8YXk5HTDfM3UQC',
        landmark: 'fdgs',
        lat: 26.108991978867923,
        lng: 91.79069981213378,
        title: 'yui',
        user_id: 'UA5JWxgjDOYgfXe92H0pFHwulTz2',
      },
      deliveryCharge: 20,
      grandTotal: '440.00',
      id: '5aG0RsPuze8NX00B7uR1',
      order: [
        {
          category_id: 'e00',
          cover: 'assets/imgs/pizza.jpg',
          desc: 'Great in taste',
          id: 'i1',
          name: 'Pizza',
          price: 120,
          quantity: 1,
          rating: 0,
          status: true,
          uid: 'r1',
          variation: false,
          veg: false,
        },
        {
          category_id: 'e00',
          cover: 'assets/imgs/pasta.jpg',
          desc: 'Great in taste',
          id: 'i3',
          name: 'Pasta',
          price: 150,
          quantity: 2,
          rating: 0,
          status: true,
          uid: 'r1',
          variation: false,
          veg: false,
        },
      ],
      paid: 'COD',
      restaurant: {
        address: 'Beltola Tiniali, India',
        city: '909090271',
        closeTime: '20:00',
        cover: 'assets/imgs/restaurant-1.jpg',
        cuisines: ['Italian', 'Mexican'],
        delivery_time: 25,
        description: 'dd',
        email: 'stay@fit.com',
        id: 'r1',
        isClose: true,
        latitude: 26.1286243,
        longitude: 91.8012675,
        name: 'Burger Chacha',
        openTime: '08:00',
        phone: 6786745745,
        price: 25,
        rating: 0,
        short_name: 'burger chacha',
        status: 'open',
        totalRating: 0,
      },
      restaurant_id: 'r1',
      status: 'Delivered',
      time: 'Jul 7, 2022 11:44 AM',
      total: '420.00',
      user_id: '1',
    },
  ];


  constructor() {}
}
